apiVersion: v1
kind: Pod
metadata:
  name: mywebapppod
  labels:
    role: webserver-role
    app: nginx
spec:
  containers:
  - name: database-server
    image: mysql-3.2
    ports:
     - containerPort: 3306